owner: webkom
repo: uptime

sites:
  - name: Abakus.no
    url: https://abakus.no/healthz
    maxResponseTime: 10000
  - name: LEGO (abakus backend)
    url: https://lego.abakus.no/health
    maxResponseTime: 5000
  - name: Abakus wiki
    url: https://wiki.abakus.no/status
    maxResponseTime: 20000

status-website:
  cname: status.abakus.no
  logoUrl: https://www.ntnu.no/documents/141712/1333881/abakus_logo-ny_Iyi5R6C.png
  name: Abakus statuspages
  introTitle: "Statuspages for abakus.no and other related services."
  introMessage: "Please report any issues in the #webkom channel in slack or send an email to webkom@abakus.no. See also #webkom in slack for details about potential issues."
  navbar:
    - title: Status
      href: /
    - title: Abakus.no
      href: https://abakus.no
